version: '3.7'

services:
  aplicacao:
    build: .
    depends_on:
      - "banco_dados"

  banco_dados:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql